[tool.ruff]
line-length = 100
target-version = "py39"

[tool.ruff.lint]
extend-select = ["E", "F", "I", "D", "DJ", "UP", "B"]
ignore = ["D100", "D104"]

[tool.ruff.lint.isort]
known-first-party = ["api_rest"]
force-single-line = false

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
